CREATE TYPE "CategoryType" AS ENUM ('POST', 'PRODUCT');
CREATE TYPE "ContentStatus" AS ENUM ('DRAFT', 'PUBLISHED');
CREATE TABLE "Category" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"type" "CategoryType" NOT NULL,"sortOrder" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Category_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Post" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"slug" TEXT NOT NULL,"excerpt" TEXT NOT NULL DEFAULT '',"content" TEXT NOT NULL,"coverImage" TEXT NOT NULL DEFAULT '',"coverImageAlt" TEXT NOT NULL DEFAULT '',"categoryId" TEXT NOT NULL,"status" "ContentStatus" NOT NULL DEFAULT 'DRAFT',"authorName" TEXT NOT NULL DEFAULT 'HONG LIANG',"seoTitle" TEXT NOT NULL DEFAULT '',"seoDescription" TEXT NOT NULL DEFAULT '',"publishedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Post_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Product" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,"model" TEXT NOT NULL DEFAULT '',"shortDescription" TEXT NOT NULL DEFAULT '',"description" TEXT NOT NULL,"categoryId" TEXT NOT NULL,"coverImage" TEXT NOT NULL DEFAULT '',"features" JSONB NOT NULL DEFAULT '[]',"specifications" JSONB NOT NULL DEFAULT '[]',"applications" JSONB NOT NULL DEFAULT '[]',"status" "ContentStatus" NOT NULL DEFAULT 'DRAFT',"sortOrder" INTEGER NOT NULL DEFAULT 0,"seoTitle" TEXT NOT NULL DEFAULT '',"seoDescription" TEXT NOT NULL DEFAULT '',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Product_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProductImage" ("id" TEXT NOT NULL,"productId" TEXT NOT NULL,"url" TEXT NOT NULL,"alt" TEXT NOT NULL DEFAULT '',"sortOrder" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ProductImage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Media" ("id" TEXT NOT NULL,"url" TEXT NOT NULL,"fileName" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"size" INTEGER NOT NULL,"alt" TEXT NOT NULL DEFAULT '',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Media_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Category_slug_key" ON "Category"("slug");
CREATE INDEX "Category_type_sortOrder_idx" ON "Category"("type", "sortOrder");
CREATE UNIQUE INDEX "Post_slug_key" ON "Post"("slug");
CREATE INDEX "Post_status_publishedAt_idx" ON "Post"("status", "publishedAt");
CREATE INDEX "Post_categoryId_status_idx" ON "Post"("categoryId", "status");
CREATE UNIQUE INDEX "Product_slug_key" ON "Product"("slug");
CREATE INDEX "Product_status_sortOrder_idx" ON "Product"("status", "sortOrder");
CREATE INDEX "Product_categoryId_status_idx" ON "Product"("categoryId", "status");
CREATE INDEX "ProductImage_productId_sortOrder_idx" ON "ProductImage"("productId", "sortOrder");
CREATE INDEX "Media_createdAt_idx" ON "Media"("createdAt");
ALTER TABLE "Post" ADD CONSTRAINT "Post_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Product" ADD CONSTRAINT "Product_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProductImage" ADD CONSTRAINT "ProductImage_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
