import Link from 'next/link';
import { prisma } from '@/lib/prisma';
import { deleteCategory, saveCategory } from '../../actions';

export default async function CategoriesPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const q = await searchParams; const type = q.type === 'POST' || q.type === 'PRODUCT' ? q.type : undefined;
  const [items, editing] = await Promise.all([prisma.category.findMany({ where:{ type, name:q.search?{contains:q.search,mode:'insensitive'}:undefined }, include:{_count:{select:{posts:true,products:true}}}, orderBy:[{type:'asc'},{sortOrder:'asc'}] }), q.edit?prisma.category.findUnique({where:{id:q.edit}}):null]);
  return <><header className="admin-page-head"><div><span>CONTENT STRUCTURE</span><h1>Categories</h1></div></header>{q.error?<p className="admin-notice error">{q.error}</p>:null}<div className="admin-split"><section><form className="admin-filter"><input name="search" placeholder="Search categories" defaultValue={q.search}/><select name="type" defaultValue={q.type||''}><option value="">All types</option><option>POST</option><option>PRODUCT</option></select><button>Filter</button></form><div className="admin-table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Slug</th><th>Used</th><th>Order</th><th/></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td><span className="admin-pill">{item.type}</span></td><td>{item.slug}</td><td>{item._count.posts+item._count.products}</td><td>{item.sortOrder}</td><td className="admin-row-actions"><Link href={`/admin/categories?edit=${item.id}`}>Edit</Link><form action={deleteCategory}><input type="hidden" name="id" value={item.id}/><button disabled={Boolean(item._count.posts+item._count.products)}>Delete</button></form></td></tr>)}</tbody></table></div></section><form action={saveCategory} className="admin-panel admin-form"><h2>{editing?'Edit category':'New category'}</h2>{editing?<input type="hidden" name="id" value={editing.id}/>:null}<label>Name<input name="name" required defaultValue={editing?.name}/></label><label>Slug<input name="slug" placeholder="auto-generated-from-name" defaultValue={editing?.slug}/></label><label>Type<select name="type" defaultValue={editing?.type||'POST'}><option>POST</option><option>PRODUCT</option></select></label><label>Sort order<input name="sortOrder" type="number" min="0" defaultValue={editing?.sortOrder||0}/></label><label>Description<textarea name="description" defaultValue={editing?.description}/></label><button className="admin-primary">Save category</button></form></div></>;
}
